name: Auto Approve and Merge Bot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug PR info
        run: |
          echo "=== PR DEBUG INFO ==="
          echo "PR author: '${{ github.event.pull_request.user.login }}'"
          echo "PR title: '${{ github.event.pull_request.title }}'"
          echo "Event action: '${{ github.event.action }}'"
          echo "Expected author: 'piecesdocumentationbot'"
          echo "Author match: ${{ github.event.pull_request.user.login == 'piecesdocumentationbot' }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "=== LABELS DEBUG ==="
          echo "PR labels: ${{ toJSON(github.event.pull_request.labels) }}"

  auto-approve:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'piecesdocumentationbot' || 
      contains(github.event.pull_request.labels.*.name, 'auto-mirror')
    needs: debug
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Debug condition check
        run: |
          echo "=== CONDITION DEBUG ==="
          echo "Bot check: ${{ github.event.pull_request.user.login == 'piecesdocumentationbot' }}"
          echo "Label check: ${{ contains(github.event.pull_request.labels.*.name, 'auto-mirror') }}"
          echo "Either condition met - proceeding with approval"
      
      - name: Check if already approved
        id: check_approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.issue.number
            
            // Check if PR is already approved by this bot
            const reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number
            })
            
              review.user.login === 'piecesdocumentationapprovebot' && 
              review.state === 'APPROVED'
            )
            
            if (botApproval) {
              console.log('PR already approved by bot, skipping...')
              core.setOutput('already_approved', 'true')
              return
            }
            
            core.setOutput('already_approved', 'false')
      
      - name: Auto-approve PR
        if: steps.check_approval.outputs.already_approved == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_APP_TOKEN }}  # Use GitHub App token with approval permissions
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.issue.number
            
            // Approve the PR
            await github.rest.pulls.createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE',
              body: 'Auto-approved: Documentation update from piecesdocumentationbot'
            })
            
            console.log(`Auto-approved PR #${pull_number}`)
      
      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.issue.number
            
            try {
              // Enable auto-merge with squash strategy
              await github.rest.pulls.enableAutoMerge({
                owner,
                repo,
                pull_number,
                merge_method: 'squash'
              })
              
              console.log(`Enabled auto-merge for PR #${pull_number}`)
            } catch (error) {
              console.log(`Could not enable auto-merge: ${error.message}`)
              
              // Comment with the issue
              await github.rest.issues.createComment({
                issue_number: pull_number,
                owner,
                repo,
                body: `**Auto-merge could not be enabled**
                
                The PR has been approved but auto-merge failed. This might be due to:
                - Branch protection rules not being fully satisfied
                - Missing required status checks
                - Other repository settings
                
                Manual merge may be required.`
              })
            }
      
      - name: Add labels and comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.issue.number
            
            // Add labels
            await github.rest.issues.addLabels({
              issue_number: pull_number,
              owner,
              repo,
              labels: ['documentation', 'bot-generated', 'auto-approved', 'verified-commits']
            })
            
            // Add success comment
            await github.rest.issues.createComment({
              issue_number: pull_number,
              owner,
              repo,
              body: `**Auto-approved and ready to merge**
              
              This documentation update from @piecesdocumentationbot has been:
              - Automatically approved by GitHub App (satisfies "different approver" requirement)
              - Commits are unsigned (may require manual merge)
              - Auto-merge enabled (squash)
              - Labeled appropriately
              
              Note: If branch protection requires signed commits, manual merge may be needed.`
            })
            
            console.log(`Added labels and comment to PR #${pull_number}`)
