name: Auto Approve and Merge Bot PRs

on:
  pull_request:
    types: [opened]  # Only trigger once when PR is created

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'piecesdocumentationbot'
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      
      - name: Check if already processed
        id: check_processed
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.issue.number
            
            const reviews = await github.rest.pulls.listReviews({ owner, repo, pull_number })
            
            const botApproval = reviews.data.find(review => 
              review.user.login === 'piecesdocumentationapprovebot' && 
              review.state === 'APPROVED'
            )
            
            core.setOutput('already_approved', botApproval ? 'true' : 'false')
      
      - name: Auto-approve and enable auto-merge
        if: steps.check_processed.outputs.already_approved == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.issue.number
            
            // Approve the PR
            await github.rest.pulls.createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE',
              body: 'Auto-approved: Documentation update from piecesdocumentationbot'
            })
            
            // Enable auto-merge
            try {
              await github.rest.pulls.enableAutoMerge({
                owner,
                repo,
                pull_number,
                merge_method: 'squash'
              })
              console.log(`Approved and enabled auto-merge for PR #${pull_number}`)
            } catch (error) {
              console.log(`Auto-merge may already be enabled: ${error.message}`)
            }
